version: "3.9"
name: apps
services:
  #---------------------------------------
  # The main app services
  #---------------------------------------
  db:
    image: postgres:15.3
    restart: unless-stopped
    ports:
      - 5432:5432
    env_file: ./env/db.env
    volumes:
      - /data/volumes/postgres:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    restart: unless-stopped
    ports:
      - 8080:8080
    env_file: ./env/keycloak.env
    volumes:
      - /data/volumes/keycloak:/opt/jboss/keycloak/standalone/data
    command: ["start-dev"]

  t3:
    platform: "linux/amd64"
    build:
      context: https://github_pat_<KEY>@github.com/abdeltif-b/app-t3.git#<BRANCHE_NAME>
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_SYNCFUSION_LICENSE: <ANY_COMMUNITY_LICENSE>
        NEXT_PUBLIC_BATCH_FUNCTION: madecDeploiementBatch
        NEXT_PUBLIC_ACCESS_KEY_ID: <KEY_ID>
        NEXT_PUBLIC_SECRET_KEY: <SECRET_KEY>
        NEXT_PUBLIC_DATA_UPLOAD_BUCKET_NAME: <BRANCHE_NAME>
        NEXT_PUBLIC_ENVIRONMENT: dev
        NEXT_PUBLIC_CLIENT: <NEXT_PUBLIC_CLIENT>
    ports:
      - 80:80
    restart: unless-stopped
    env_file: ./env/t3.env
    volumes:
      - /data/uploads/Fichiers importés:/data/uploads/Fichiers importés
    depends_on:
      - db
      - keycloak

  functions:
    build:
      context: https://github_pat_<KEY>@github.com/abdeltif-b/app-functions.git#<BRANCHE_NAME>
      dockerfile: Dockerfile
    volumes:
      - /data/uploads/Fichiers importés:/data/uploads/Fichiers importés
    ports:
      - 8000:8000
    restart: unless-stopped
    env_file: ./env/functions.env
    depends_on:
      - db
      - t3

  pgbackups:
    image: prodrigestivill/postgres-backup-local
    restart: unless-stopped
    env_file: ./env/pgbackups.env
    volumes:
      - /data/volumes/pgbackups:/backups
    depends_on:
      - db

  #---------------------------------------
  # grafana / prometheus related services
  #---------------------------------------
  grafana:
    image: grafana/grafana
    restart: unless-stopped
    ports:
      - 3001:3000
    # run as root user
    user: "0"
    environment:
      - GF_SECURITY_ADMIN_USER=user
      - GF_SECURITY_ADMIN_PASSWORD=pass
    volumes:
      # automatically configure the loki datasource
      - ./grafana_files/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      # directory must be created first, with uid:gid 472:472
      - /data/volumes/grafana:/var/lib/grafana

  loki:
    image: grafana/loki:2.6.1
    ports:
      - 3100:3100
    user: "0"
    volumes:
      # directory must be created first, with uid:gid 10001:10001
      - /data/volumes/loki:/loki

  # https://cylab.be/blog/241/use-loki-to-monitor-the-logs-of-your-docker-compose-application
  promtail:
    image: grafana/promtail:2.6.1
    restart: unless-stopped
    volumes:
      # custom config will read logs from the containers of this project
      - ./grafana_files/promtail-config.yaml:/etc/promtail/config.yml
      # to read container labels and logs
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers

  prometheus:
    image: prom/prometheus
    restart: unless-stopped
    ports:
      - 9090:9090
    user: "0"
    volumes:
      - ./grafana_files/prometheus.yml:/etc/prometheus/prometheus.yml
      - /data/volumes/prometheus:/prometheus

    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--web.enable-lifecycle"

  postgres-exporter:
    image: quay.io/prometheuscommunity/postgres-exporter
    restart: unless-stopped
    environment:
      DATA_SOURCE_NAME: "postgresql://user:pass@db:5432/db_name?sslmode=disable"
    ports:
      - "9187:9187"

  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    restart: unless-stopped
    command:
      - "--path.rootfs=/host"
    ports:
      - "9100:9100"

    volumes:
      - "/:/host:ro,rslave"
